# Generated by Django 5.2.3 on 2025-07-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(default='', help_text='Name of the video', max_length=500)),
                ('frame_index', models.IntegerField(default=0, help_text='Frame index in the video')),
                ('url', models.TextField(default='', help_text='URL of the frame image')),
                ('qa', models.TextField(blank=True, help_text='Question and answer text', null=True)),
                ('query_index', models.IntegerField(default=0, help_text='Query index number (default: 0)')),
                ('round', models.CharField(choices=[('prelims', 'Prelims'), ('final', 'Final')], default='prelims', help_text='Round type: prelims or final', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'db_table': 'answer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(help_text='Name of the video', max_length=500)),
                ('frame_index', models.IntegerField(help_text='Frame index in the video')),
                ('url', models.TextField(help_text='URL of the frame image')),
                ('qa', models.TextField(blank=True, help_text='Question and answer text', null=True)),
                ('query_index', models.IntegerField(default=0, help_text='Query index number (default: 0)')),
                ('round', models.CharField(choices=[('prelims', 'Prelims'), ('final', 'Final')], default='prelims', help_text='Round type: prelims or final', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Answer',
                'verbose_name_plural': 'Team Answers',
                'db_table': 'team_answer',
                'ordering': ['-created_at'],
                'unique_together': {('video_name', 'frame_index', 'query_index')},
            },
        ),
    ]
