# Generated by Django 5.2.3 on 2025-08-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTRAKEAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(help_text='Name of the video', max_length=500)),
                ('frame_index', models.IntegerField(help_text='Frame index in the video')),
                ('url', models.TextField(help_text='URL of the frame image')),
                ('query_index', models.IntegerField(default=0, help_text='Query index number (default: 0)')),
                ('round', models.CharField(choices=[('prelims', 'Prelims'), ('final', 'Final')], default='prelims', help_text='Round type: prelims or final', max_length=10)),
                ('group', models.CharField(default='default', help_text='Group identifier for grouping multiple TeamTRAKEAnswer instances', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team TRAKE Answer',
                'verbose_name_plural': 'Team TRAKE Answers',
                'db_table': 'team_trake_answer',
                'ordering': ['-created_at'],
            },
        ),
    ]
