# Generated by Django 5.2.3 on 2025-08-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamanswer',
            name='qa',
            field=models.CharField(blank=True, default='', help_text='Question and answer text', max_length=100),
        ),
    ]
