# Generated by Django 5.2.3 on 2025-08-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_teamtrakeanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtrakeanswer',
            name='group',
            field=models.IntegerField(default=0, help_text='Group identifier for grouping multiple TeamTRAKEAnswer instances'),
        ),
    ]
