# Generated by Django 5.2.3 on 2025-09-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_alter_teamanswer_qa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DresSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Username used for DRES login', max_length=255)),
                ('role', models.CharField(help_text='User role in DRES system', max_length=50)),
                ('session_id', models.CharField(help_text='DRES session ID from server', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DRES Session',
                'verbose_name_plural': 'DRES Sessions',
                'db_table': 'dres_session',
                'ordering': ['-created_at'],
            },
        ),
    ]
