# Generated by Django 5.2.3 on 2025-08-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0003_alter_teamtrakeanswer_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamtrakeanswer',
            name='round',
        ),
    ]
