services:
  dres:
    build: .
    container_name: dres
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - type: bind
        source: ./dres_media
        target: /data/media 
      - dres-data:/dres-dist/lib/data  
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  dres-data:
