# Generated by Django 5.2.3 on 2025-07-05 03:47

import django.db.models.deletion
import django.utils.timezone
import query.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(default='', help_text='Name of the video', max_length=500)),
                ('frame_index', models.IntegerField(default=0, help_text='Frame index in the video')),
                ('url', models.TextField(default='', help_text='URL of the frame image')),
                ('qa', models.TextField(blank=True, help_text='Question and answer text', null=True)),
                ('query_index', models.IntegerField(default=0, help_text='Query index number (default: 0)')),
                ('round', models.CharField(choices=[('prelims', 'Prelims'), ('final', 'Final')], default='prelims', help_text='Round type: prelims or final', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'db_table': 'answer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuerySession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Query Session',
                'verbose_name_plural': 'Query Sessions',
                'db_table': 'query_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, help_text='Text content of the query', null=True)),
                ('ocr', models.TextField(blank=True, help_text='OCR extracted text', null=True)),
                ('speech', models.TextField(blank=True, help_text='Speech-to-text content', null=True)),
                ('image', models.ImageField(blank=True, help_text='Uploaded image for the query', null=True, upload_to=query.models.query_image_upload_path)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the query was created')),
                ('background_sound', models.TextField(blank=True, help_text='Background sound information', null=True)),
                ('stage', models.PositiveIntegerField(default=1, help_text='Stage number for query processing (default: 1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, help_text='Session this query belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='query.querysession')),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
                'db_table': 'query',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(help_text='Name of the video', max_length=500)),
                ('frame_index', models.IntegerField(help_text='Frame index in the video')),
                ('url', models.TextField(help_text='URL of the frame image')),
                ('qa', models.TextField(blank=True, help_text='Question and answer text', null=True)),
                ('query_index', models.IntegerField(default=0, help_text='Query index number (default: 0)')),
                ('round', models.CharField(choices=[('prelims', 'Prelims'), ('final', 'Final')], default='prelims', help_text='Round type: prelims or final', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Answer',
                'verbose_name_plural': 'Team Answers',
                'db_table': 'team_answer',
                'ordering': ['-created_at'],
                'unique_together': {('video_name', 'frame_index', 'query_index')},
            },
        ),
    ]
